name: Rust

on:
  # push:
    # branches: [ "master" ]
  schedule:
    - cron: '30 01 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # 设置环境变量
    - name: Set environment variables
      env:
        OFFICIAL_APP_ID: ${{ secrets.OFFICIAL_APP_ID }}
        OFFICIAL_APP_SECRET: ${{ secrets.OFFICIAL_APP_SECRET }}
        BAIDU_AK: ${{ secrets.BAIDU_AK }}
        PUSH_ID: ${{ secrets.PUSH_ID }}
        TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
        LOVE_DAYS: ${{ secrets.LOVE_DAYS }}
      run: echo "Environment variables set"
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      env:
        OFFICIAL_APP_ID: ${{ secrets.OFFICIAL_APP_ID }}
        OFFICIAL_APP_SECRET: ${{ secrets.OFFICIAL_APP_SECRET }}
        BAIDU_AK: ${{ secrets.BAIDU_AK }}
        PUSH_ID: ${{ secrets.PUSH_ID }}
        TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
        LOVE_DAYS: ${{ secrets.LOVE_DAYS }}
        
      run: cargo run
